import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  apiSidebar: [
    {
      type: 'category',
      label: 'API Reference',
      collapsible: true,
      items: [
        'api/index', // Main API Page
        'api/globals', // If needed
        { type: 'autogenerated', dirName: 'api/functions' },
      ],
    },
  ],

  guidesSidebar: [
    {
      type: 'category',
      label: 'Guides & Documentation',
      collapsible: true,
      items: [
        'guides/DOCS_INDEX',
        'guides/INSTALLATION',
        'guides/API_REFERENCE',
        'guides/USAGE',
        'guides/CHANGELOG',
        'guides/CODE_OF_CONDUCT',
      ],
    },
  ],
};

export default sidebars;
