import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  apiSidebar: [
    {
      type: 'category',
      label: 'API Reference',
      collapsible: true,
      items: [
        'api/index', // Main API Page
        'api/globals', // If needed
        { type: 'autogenerated', dirName: 'api/functions' },
      ],
    },
  ],
};

export default sidebars;
