name: Deploy Docusaurus Docs to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual deployment

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Root Dependencies
        run: npm install

      - name: Install Docusaurus Dependencies
        run: |
          cd docs
          npm install

      - name: Build Docusaurus
        run: npm run docs:build

  deploy-pages:
    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd docs/build
        git init
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Deploy Docusaurus docs"
        git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main:gh-pages
