name: Run Jest Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # Fail if no test files exist
      - name: Ensure test files exist
        run: |
          if ! find ./tests ./src -type f -name "*.test.ts" -o -name "*.test.js" | grep .; then
            echo "::error::No test files found! PRs require tests."
            exit 1
          fi

      # Run Jest tests and fail if they don't pass
      - name: Run Jest tests
        run: npm test -- --coverage

      # Upload Jest test results (always run, even if previous steps fail)
      - name: Upload Jest test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jest-results
          path: coverage
